services:
  # Backend Node.js
  - type: web
    name: liguey-backend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: 32d4d0fac879c7d73ada85006c653c36f807b09f7c9d886f7add85e50202acb5a7ba7435eaac7f59bd4f75213fbccb7a887611feac763375be8d688b92e508ab
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 10
      - key: FRONTEND_URL
        value: https://liguey-connect.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: liguey-mysql
          property: connectionString

databases:
  # Base de données MySQL
  - name: liguey-mysql
    databaseName: liguey_connect
    user: liguey_user
    region: frankfurt
    plan: free